windows:
  5s: 5
  15s: 15
  60s: 60

burst:
  growth_thresholds:
    5s: 1.5
    15s: 1.4
    60s: 1.3
  min_prev_count: 1

alerts:
  confirm_count: 2
  cooldown: 10

severity:
  window_weights:
    5s: 1
    15s: 2
    60s: 3
  ttl: 20

bloom:
  size: 50000
  hash_count: 6
  rotate_interval: 10
